src/main.rs
I am about to replace my own little update-shellscript with topgraph as it offers better reporting and overall, is the higher-quality way of doing it.
Probably I will just keep pushing into this PR until it's done, or you tell me to stop :D.
=> Update a few more things

README.md
👋 @r-darwish This PR updates the name and link to fisher in the README. Thanks.
=> doc: update name and link to fisher

.travis.yml, appveyor.yml
=> Do not perform CI on bors temporary branches

src/steps/generic.rs
=> Canonicalize rustup path before checking if its origin (fix #124)

src/main.rs, src/steps/os/linux.rs
=> More step refactoring

src/steps/os/unix.rs
Check ZPLUG_HOME environment variable in addition to ~/.zplug. Also consider ZDOTDIR when sourcing
.zshrc.
=> fix(zplug): search appropriate paths for zplug folder

src/config.rs, src/main.rs
=> Add a flag for disabling Powershell

src/main.rs, src/steps/os/unix.rs
=> Refactor unix steps

src/main.rs, src/steps/emacs.rs, src/steps/generic.rs, src/steps/mod.rs
=> Better Emacs handling in Windows (fix #112)

src/steps/os/linux.rs
Solus uses "eopkg" for system package management.
=> Added support for Solus Linux distro

src/steps/git.rs
=> Show what's new in Git repositories

src/steps/os/linux.rs
This change also updates development packages when using yay.
=> Update development packages using yay

src/main.rs, src/utils.rs
sudo might not be available everywhere and pkexec works just as well (if not better) for this kind of things
=> allow pkexec to be used instead of sudo

src/steps/os/linux.rs
"No sudo or yay" => "Not sudo nor yay"
=> Fix grammar

README.md, src/main.rs, src/steps/os/unix.rs
Support for https://github.com/zsh-users/antigen
=> Added support for antigen

config.example.toml, src/config.rs, src/main.rs, src/steps/os/linux.rs
@r-darwish Should I add tests somewhere? didn't figure out where.. :)
=> Support yay arguments in config file (Closes #220)

README.md, src/main.rs, src/steps/vim.rs
https://github.com/airblade/voom
=> Added support for Voom for Vim packages

README.md, src/main.rs, src/steps/generic.rs
https://docs.haskellstack.org/en/stable/README/
=> Add stack support

README.md, src/main.rs, src/steps/os/linux.rs, src/steps/os/os_release/nixos, src/steps/os/unix.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/r-darwish/topgrade/253)
=> Extend support for Nix/NixOS/home-manager

src/config.rs, src/main.rs, src/steps/generic.rs
Continuation of #261 
Sorry about the inconvenience, I messed up by making cosmetic changes during the rebase which caused duplicate commits and force pushed to fix it.
=> [📦 NEW] go get -u all

src/main.rs, src/steps/zsh.rs
This pull request adds additional plugin manager to the zsh steps.
=> Add zplugin to zsh steps

src/main.rs
=> Move rpi-update under config.should_run(Step::Firmware)

README.md
Golang was feeling left out from the list of steps taken during a topgrade.
Thanks for creating such a great project!
=> Include Golang update step in README

src/steps/os/linux.rs, src/steps/os/os_release/manjaro-arm
Support Manjaro Arm by matching on ID
=> Manjaro Arm doesn't have an ID_LIKE

topgrade.8
=> Improve man page formatting

README.md
- ~[ ] The code compiles~
- ~[ ] The code passes rustfmt~
- ~[ ] The code passes clippy~
- ~[ ] The code passes tests~
- ~[ ] *Optional:* I have tested the code myself~
- ~[ ] I also tested that Topgrade skips the step where needed~
=> macOS config file was moved under user home

src/steps/os/linux.rs, src/steps/os/os_release/rhel
I'm not sure if this is how you'd like to handle support RHEL, but it seems to work for me, so far.
=> added rhel to CentOS

src/steps/emacs.rs
Starting with Emacs 27, Emacs now looks for an `emacs` directory in `$XDG_CONFIG_HOME` (c.f. [this commit](
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4118297ae2fab4886b20d193ba511a229637aea3)) if no `~/.emacs.d` directory is present, so we better do that as well.
=> Look for Emacs directory in $XDG_CONFIG_HOME

src/steps/git.rs
I have selected many git repos for automatic update by using a wide glob. Some of these repos don't have a remote yet so I always have to tell topgrade to ignore the failed pulls on these repos. I could probably just tell topgrade to always ignore errors in the git step but I think it would still show up as failed. 
This PR simply skips git repos without remotes but still logs a warning that this is happening. I would really like to see this merged, so let me know if I can improve anything!
=> Skip git repos without remotes

src/steps/os/linux.rs
=> Don't run fwupdmgr in WSL

src/config.rs, src/main.rs, src/steps/os/macos.rs, src/terminal.rs
=> Ask before installing macOS upgrades

src/main.rs
=> Correct npm's capitalization in summary

src/config.rs, src/main.rs, src/steps/os/unix.rs
=> Support yadm (fix #464)

src/steps/powershell.rs
=> Run Windows update with Powershell using sudo (fix #477)

Cargo.lock, Cargo.toml, src/main.rs
=> Restore openssl-probe

Cargo.lock, Cargo.toml, src/config.rs, src/main.rs
=> Add flag for limit execution to specific remote hosts (fix #491)

README.md
=> Add --remote-host-limit note to README.md

Cargo.lock, Cargo.toml
=> bump dependencies

src/steps/upgrade.vim
=> Support Vim's package (fix #498)

src/steps/os/linux.rs, src/steps/os/os_release/artix
=> Fix garuda linux detection

src/config.rs, src/main.rs, src/steps/generic.rs
=> Add choosenim (fix #511)

src/config.rs, src/main.rs
=> Add post-commands (fix #505)

src/main.rs, src/steps/os/unix.rs
=> Add oh-my-fish (fix #513)

src/main.rs, src/steps/os/unix.rs
=> Fix oh-my-fish

src/config.rs, src/main.rs, src/steps/generic.rs
- R tools for the command line
- https://github.com/rdatsci/rtcl
- Like Jetpack, but more powerful.
**`rupdate`'s a sub command from `rtcl` package, and I don't know how to properly name it in topgrade**
=> Add rtcl::rupdate

src/main.rs, src/steps/os/macos.rs, src/steps/os/unix.rs
=> Deprecate the brew cask step (fix #520)

src/config.rs, src/main.rs, src/steps/node.rs
Hi, sorry for the double PR.  This merge is targeted to `master` branch in the main repo, instead of `deno` branch (which was an error on my part).
Addresses #526.
=> Add deno upgrade

src/steps/git.rs
The `git submodule update` command, run as part of updating a git repo,
caused output corruption on Windows.  The effect was to disable
ANSI/VT100 control sequence processing on the terminal.
While the root cause isn't clear this is almost certainly caused by some
component of the mingw chain setting the Windows "console mode" field to
disable escape sequence processing as part of resetting it to "normal"
for the platform.
With some experimentation I determined that setting the stdin handle for
the `git submodule` process would alter the behaviour, preventing the
problem.  Again, no root cause, but this almost certainly changes the
understanding that some subprocess has to "no terminal" rather than
"attached to a terminal."
Only `Stdin::null()` worked for this; piped or inherited stdin …
=> git/windows: fix output corruption when running `git submodule`

src/main.rs, src/steps/os/linux.rs, src/steps/remote/vagrant.rs, src/steps/zsh.rs
Zim is a Zsh configuration framework. See https://github.com/zimfw/zimfw
=> Add support to Zim

src/steps/zsh.rs
=> Fix oh-my-zsh (fix #567)

src/steps/os/linux.rs
=> Use distro-sync in dnf (fix #576)

src/utils.rs
=> Prefer doas over sudo (fix #576)

src/config.rs, src/main.rs, src/steps/os/unix.rs
=> Split brew cask into a seperate step (fix #588)

Cargo.lock, Cargo.toml, src/steps/git.rs, src/steps/remote/vagrant.rs
=> Dependencis bump

src/steps/node.rs
=> Missing cfg

src/steps/os/unix.rs
=> Fix Linuxbrew (fix #616)

src/config.rs, src/main.rs, src/steps/os/unix.rs
=> Bash-it (fix #621)

src/config.rs, src/main.rs, src/steps/os/windows.rs, src/steps/powershell.rs
=> Windows App Store (fix #622)

src/config.rs, src/main.rs, src/steps/generic.rs
=> added support for Visual Studio Code (VSC) extension update

src/config.rs, src/main.rs, src/steps/generic.rs
=> Fossil support

src/steps/os/unix.rs
=> Run bash-it with the interactive flag (fix #642)

src/steps/os/unix.rs
=> Fix nix on multi-user setup (fix #646)

.github/workflows/main.yml
https://github.com/actions/checkout/blob/main/CHANGELOG.md
=> GitHub Actions: Upgrade checkout

.github/PULL_REQUEST_TEMPLATE.md
Pull Template: the checklist should be more precise what/how to test
=> Pull Template: the checklist should be more precise what/how to test

src/config.rs, src/main.rs, src/steps/generic.rs
=> Support for PIP3 (self update)

src/config.rs, src/main.rs, src/steps/generic.rs
=> Racket package manager support

src/main.rs, src/steps/generic.rs
=> Avoid displaying unnecessary Cargo warning (fix #671)

src/main.rs, src/steps/os/linux.rs
=> Run fwupdmgr update (fix #668)

src/steps/os/linux.rs
KDE Neon is Ubuntu based and uses `pkcon` and PackageKit instead of `apt`. It errors if you try and use `apt`
~~~
On KDE neon you should use `pkcon update` to install updates.
If you absolutely must use apt you do have to use dist-upgrade or full-upgrade in place of the upgrade command.
https://neon.kde.org/faq#command-to-update
Abort.
~~~
In theory anything can use PackageKit, in practice it doesn't look like anything other than KDE Neon does by default these days. I made a note of this in the comments for future spelunkers if this ever comes up again.
I have never worked with rust before, sorry.
=> Use pkcon over apt with kde neon

src/main.rs, src/steps/os/unix.rs
https://github.com/kidonng/fish-plug
- [y] The PR title is descriptive.
- [y] The code compiles (`cargo build`)
- [y] The code passes rustfmt (`cargo fmt`)
- [y] The code passes clippy (`cargo clippy`)
- [y] The code passes tests (`cargo test`)
- [y] *Optional:* I have tested the code myself
=> Added support for fish-plug

src/config.rs, src/main.rs, src/steps/os/macos.rs
=> Remove msupdate (fix #698)

src/steps/os/windows.rs
=> No need to run which in WSL (fix #694)

src/config.rs, src/main.rs, src/steps/os/macos.rs
=> Add silnite support (fix #701)

src/config.rs, src/main.rs, src/steps/os/windows.rs
=> Support winget (fix #721)

src/steps/generic.rs
=> Better cargo detection (fix #724)

config.example.toml, src/config.rs, src/main.rs, src/steps/node.rs
=> Allow running NPM as sudo (fix #690)

src/steps/generic.rs
=> Don't run pip in a virtual environment

src/main.rs, src/steps/os/linux.rs
Closes #800. Can't test since i'm on windows currently.
=> Implement cleanup for flatpak

src/steps/os/linux.rs
=> Support yes flag for Void

src/main.rs, src/steps/os/macos.rs
=> Remove-slinite

.vscode/topgrade.code-snippets, src/steps/generic.rs, src/steps/os/windows.rs
=> Gh-extensions

config.example.toml, src/config.rs, src/main.rs, src/terminal.rs
=> Remove-time

src/execution_context.rs, src/steps/os/linux.rs, src/steps/os/unix.rs
=> Execute-elevated

config.example.toml, src/config.rs, src/steps/os/archlinux.rs
=> Add pikaur support

.vscode/launch.json, .vscode/topgrade.code-snippets, src/main.rs, src/steps/remote/vagrant.rs
=> Vagrant boxes

src/main.rs, src/steps/vim.rs
=> "Ultimate vimrc" support

Cargo.lock, Cargo.toml, src/main.rs
=> Use rustls (fix #906)

Cargo.toml
=> Fix self-update

.github/workflows/main.yml
=> Fix workflow

src/terminal.rs
=> No 'failed step' notification

src/config.rs, src/main.rs
=> Add the --env flag

.vscode/launch.json, src/config.rs, src/main.rs
=> Add --custom-command

src/terminal.rs
=> Desktop notifications show step in summary

.vscode/topgrade.code-snippets, src/main.rs, src/steps/os/unix.rs
=> Mac OS fails to upgrade Homebrew in custom location

src/steps/upgrade.vim
Upgrade vim-coc plugins.
I've tested this by running the Vim script myself. Seems to work.
=> [vim] Update Coc plugins

Cargo.lock, Cargo.toml
=> Avoid linking with libssl

src/steps/zsh.rs
=> Stop checking ZPFX

src/config.rs, src/main.rs, src/steps/node.rs
=> Don't make pnpm a seperate step

src/steps/containers.rs
=> Don't try to update devcontainers

.github/ISSUE_TEMPLATE/bug_report.md
=> Update bug_report.md with improved hints
