README.md
src/generic.rs
src/main.rs

This adds support for the [OCaml package manager](https://opam.ocaml.org/) (OPAM).
The command line `opam update` first performs a self-update if necessary. Then it updates its package list.
Finally, `opam upgrade` upgrades all locally installed packages.

Add OCaml package manager (OPAM)

---

README.md
src/config.rs
src/main.rs
src/unix.rs

If you are using applications like brew they may keep a history of
packages downloaded. Especially the bigger your number of installed
packages for homebrew gets the bigger those directories get. This can
quickly add up to a couple of GBs.
In my current workflow of updating, I was always cleaning up homebrews / linuxbrews "unneeded" resources after running it.
This pull-request adds a new flag to topgrade that enables users to explicitly ask for removing those kind of files. The PR contains an implementation for "brew" but it can easily spread to other commands as well.

Adding a new flag for cleaning up old resources

---

README.md
src/config.rs
src/main.rs

Just like we have the `--no-emacs` flag, it would be nice to have the `--no-vim` flag, to avoid the upgrade of the vim/neovim configuration files and packages.

Add `--no-vim` flag

---

src/config.rs
src/main.rs

Just like we have the other `--no-X` flags, it would be nice to have the `--no-ruby` flag, to avoid the upgrade of the ruby gems on systems that have gems installed and managed by the system package manager in a way that require additional configuration steps for us to be able to upgrade them.
For example, I have an Arch system that has ruby and rubygems installed and managed by pacman as part of dependencies for vagrant. Topgrade occasional fails when trying to upgrade some of the gems that are installed due to missing environment variables.

Add `--no-ruby` flag

---

appveyor.yml
ci/script.sh
src/steps/git.rs
src/utils.rs

While `//?/C:/Users/Someone/config-files` is a valid path, it's not very human friendly.
Such paths are returned from `BaseDirs`. This patch formats them in the traditional way.

Normalize paths in Windows (fix #113)

---

README.md
src/main.rs
src/steps/os/dragonfly.rs
src/steps/os/mod.rs

DragonFly BSD supports the same pkg upgrade and audit of FreeBSD, though the OS upgrade process is different.

Add DragonFly BSD support

---

src/steps/os/linux.rs
src/steps/os/os_release/gentoo

Some older installs have both `/etc/os-release` and `/etc/gentoo-release`. This commit fixes them not being identified.

 Support ID=gentoo in /etc/os-release 

---

src/config.rs

The current documentation for this option does not make sense and the
documentation for the keep_at_end function differs. I made this change
assuming is a typo.

Fix typo for keep option

---

src/config.rs
src/main.rs
src/steps/generic.rs

Can be used to add SSH command-line arguments like `-o
ConnectTimeout=2`

Add an ssh_arguments configuration file field

---

src/config.rs
src/main.rs

This should add the option to disable node package updates in the `topgrade.toml` config.
I've put the different node-based package managers under the same name `"node"`, but some users might prefer more fine-grained control over each package manager. That should be considered in the future.
Alas, this is what I needed.

Add option to disable node package updates

---

src/main.rs

This makes them easier to disable

Add Flatpak and snap to Step::System

---

README.md
src/main.rs
src/steps/os/unix.rs

[zr](https://github.com/jedahan/zr) is a simple zsh package manager, written in rust.
I tried to keep this as similar as possible to the other update mechanism, but do have a few questions for the future:
1. Should we use deeper integration by bringing making `zr` a library and bringing it in as a dependency in the future?
2. Should we really be sourcing the entirety of zshrc when doing shell stuff? Feels side-effecty, but if thats the best way to have the right paths for everything, *shrug*?
3. Should I just make the above two questions issues to discuss separately from this PR?

Add zr support

---

src/steps/git.rs

When there are a log of changes in the git step, topgrade might be "stack" in pager (e.g. less) until the user will manually exit it.
Using '--no-pager' flag allow all the changes to be printed to screen regardless of the amount of commits or the user's git configuration.

Use '--no-pager' flag for git-log

---

config.example.toml
src/config.rs

@r-darwish There are some parts I'm not 100% sure about the correct behavior (mostly allowed steps), let me know what you think, we can change some implementation details.
But it works :)
Notes: 
* We lose ConfigFile::read(base_dirs) logs with verbosity on, but we don't have verbosity from config before reading the config file.. I think behavior should be the same for -v and `verbose = true`. 
* It seems `yes` was already implemented but the behavior is weird, the name is `assume_yes` and the config takes precedent to the command line? :confused:

Allow most command-line options to be configured in config file (closes #188)

---

config.example.toml
src/config.rs

Note: removed verbosity from config file, as failing while reading the config file needs a logger output and env_logger can't be init twice or changed after init as far as I could tell.
@r-darwish WDYT?

Handle gracefully config path not existing (Fixes #238)

---

src/steps/emacs.rs

On emacs 26.2, when the `--eval` argument to emacs contains spaces, it results in this error: 
```
End of file during parsing
```
It is enough to reproduce this with:
```
emacs --batch --eval "(if 1 0 42)"
```
and likewise with escaping (not that it should matter):
```
emacs --batch --eval "(if\ 1\ 0\ 42)"
```
It does seem that replacing these with 0xA0 (non-breaking space) works, though, and it's the best workaround I could find, though hackish.

Fix whitespace in emacs lisp code

---

src/config.rs

If the configuration file couldn't be loaded for any reason either due to I/O problems, or deserialization errors, those problems would be completely swallowed and the default config would be used.
This PR still falls back to the default config, but it does log those configuration errors so the user can fix them (and know the exact filepath that had issues).
Resolves: #263

Log configuration errors

---

src/steps/generic.rs

* Need to use `kpsewhich` to find the directory
* Need to chomp the trailing whitespace from the result
* Need to execute `command`
I don't know rust at all - this is just the result of me changing things until it works....

Fix tlmgr step

---

src/steps/os/unix.rs

I'm using [tealdeer](https://github.com/dbrgn/tealdeer) as my tldr client and when using topgrade the ugprade didn't work because tealdeer only executed the -v command and not the --update one. This PR changes the step to also work with tealdeer.

Fix tldr upgrade when using tealdeer

---

README.md
src/config.rs
src/main.rs
src/steps/node.rs
src/steps/os/linux.rs
src/steps/os/macos.rs

macOS users install NPM using brew to /usr/local. This directory is
writable by the user

Skip the NPM root check in macOS (fix #303)

---

src/steps/os/linux.rs

Fedora Silverblue doesn't use dnf or yum for package management, rather, it uses rpm-ostree.
This pull request adds support for rpm-ostree.

Add support for Fedora Silverblue

---

src/config.rs
src/main.rs
src/steps/generic.rs

Hi, and thanks for this awesome tool.
Currently, the `valet install` command is run after `composer global update`, regardless of whether or not it is necessary. `valet install` is a very time consuming command to run, since it restarts several background services (dnsmasq, php-fpm and nginx) sequentially. It will also stop the upgrade process and prompt for a password unless the `valet` and `brew` users have been added to the sudoers file.
As far as I know, running `valet install` only makes sense if valet was updated during the composer update, so that's what this pull request tries to achieve.
I couldn't figure out how to obtain the command output from `Executor`, so in stead I'm running the `Command` directly - which means that the output isn't streamed to stdout like it should. …

Only run "valet install" if valet was updated

---

README.md
src/main.rs
src/steps/zsh.rs

This PR adds support for updating zsh plugins using [antibody](https://getantibody.github.io/).

Support update of zsh plugin with antibody

---

src/main.rs
src/steps/zsh.rs

zplugin was renamed to zinit: https://github.com/zdharma/zinit/commit/1ca8f6856cfe5e56abc969eae8e2a5489feb3a65
* s/zplugin/zinit/
* Testing for $ZPFX instead of ZPLGM which is exported

zplugin was renamed to zinit

---

src/main.rs
src/steps/zsh.rs

Checking for `.zinit` and defaulting to `zplugin` if it's not present. See discussion in #320 
@strangelittlemonkey - see if it makes sense to you
Apologies in advance if the code is not idiomatic Rust.

Better zinit renaming handling

---

src/steps/os/linux.rs

Fixes #246.
The issue is detailed in [1] and following comments.
Based on the same reasoning as for "get-updates" discussed in [2], return code 2 (EXIT_NOTHING_TO_DO) would need to be ignore for "refresh" as well.
[1] https://github.com/r-darwish/topgrade/issues/246#issuecomment-586640775-permalink
[2] https://github.com/r-darwish/topgrade/issues/246#issuecomment-549117042-permalink

[🐛 FIX] ignore EXIT_NOTHING_TO_DO for all fwupdmgr commands

---

src/steps/os/linux.rs

As per void-linux/xbps#194, `xbps-install` now forces one to first sync and upgrade `xbps` itself before doing a full system update.

Comply with new xbps behaviour

---

src/config.rs
src/main.rs
src/self_update.rs
src/utils.rs

Fix Clippy 1.43 warnings

---

src/config.rs

Fix clippy warning about useless closure

---

src/steps/os/linux.rs
src/steps/os/os_release/fedoraremixforwsl
src/steps/os/os_release/pengwinonwsl

- check for specific ID first, then check for ID_LIKE
- added case for ID_LIKE=fedora
- added test for Fedora Remix on WSL
- added test for Pengwin (Debian-like on WSL)
I hope this PR is better than my last. Regarding the reordering of the OS checks: it makes more sense to me to check for a specific ID first and then check the ID_LIKE cases. The tests run. I hope you don't mind. I'm still very new to Rust.

reorg linux os check, add ID_LIKE=fedora, add tests

---

config.example.toml
src/config.rs
src/steps/os/linux.rs

Add configuration flags for portage arguments

---

src/config.rs
src/main.rs
src/steps/generic.rs

Adds support for the kubectl plugin package manager krew
https://krew.sigs.k8s.io/

Add support for the kubectl plugin package manager krew

---

src/main.rs
src/steps/os/windows.rs

Add support for -y flag in Chocolatey

---

src/config.rs
src/steps/os/windows.rs

- gsudo runs a command with elevated privileges
- https://github.com/gerardog/gsudo

option to use choco with gsudo on windows

---

config.example.toml

Small fix. Removes a space between the comment character and the
predefined_repos option to create consistency with other options.

Remove superfluous space in config.example.toml

---

config.example.toml
src/config.rs
src/steps/generic.rs
src/steps/tmux.rs

This (slightly hacky) option provides a global method of specifying a Topgrade executable outside of the standard $PATH (see #380). For instance, to use Topgrade executables from ~/.cargo/bin, one may specify `remote_topgrade_path = ".cargo/bin/topgrade"`. The remote upgrade command will then be something along the lines of `ssh -t <host> env TOPGRADE_PREFIX=<host> .cargo/bin/topgrade`, which is then resolved relative to the user's home directory.
This implementation opts to make this a global setting rather than undertake per-remote configuration, which is likely to require significantly more effort. However, pursuing per-remote setup is likely
a worthy future goal. This implementation also supports only UTF-8 strings, i.e. std::string::String, which is internally consistent but …

Add remote_topgrade_path configuration option

---

src/steps/powershell.rs

I noticed macOS compilation failing on powershell after commit https://github.com/r-darwish/topgrade/commit/abc6a8065b5ff92d65c4eb2c21e0b95b937cf393
The change there to use `ExecutionContext` would fail because it was conditionally compiled in only on windows, but the update function would be used on all targets.

Modify powershell step to fix compilation on macOS

---

src/steps/vim.rs
src/utils.rs

Make sure VIMRC doesn't contain \r (fix #476)

---

src/steps/os/linux.rs

Don't require sudo for ostree (fix #479)

---

config.example.toml

The `remote_topgrade_path` expects a string, not an array.

Fix remote_topgrade_path example value

---

src/steps/emacs.el

In goal to close #509 
The only goal of this line is to eliminate  this message from Emacs step.
```
Would you like to set up GitHub integration?
This will allow you to star/unstar packages from the Package Menu. (y or n) 
```
We this the Emacs steps have no interaction needed

Surpass Paradox prompt in Emacs

---

src/steps/zsh.rs

ZR_HOME is removed from zr docs. And update command changed to 'zr --update'

Fix zr update

---

src/steps/upgrade.vim
src/steps/vim.rs

First off, topgrade previously didn't honor `XDG_CONFIG_HOME` and instead defaulted to a hard-coded `$HOME/.config`.
In the process, I also noticed an error for an undefined variable under NeoBundle due to missing quotes, as well as the `PlugClean` step for vim-plug not doing anything due to prompting for user input.
I'm open for discussion wrt the `PlugClean` thing, although I would personally prefer if topgrade would not unconditionally delete inactive plugins, as I personally sometimes turn some off for testing.

Fix some minor Vim issues

---

src/main.rs

Fix Jetpack typo

---

src/main.rs
src/steps/node.rs

Hi @r-darwish.  I changed the `deno` invocation to use the correct parameter.  Still working on testing this, but I should have it done very soon.  This now works on linux, so I expect it will work on the other OS's.
Resolves #526.

Add deno upgrade step (fixes #526)

---

src/config.rs

--only will execute disabled steps (fix #533)

---

src/steps/os/unix.rs

As of fisher 4.0.0 the user is expected to update fisher by installing
itself.
See: https://github.com/jorgebucaran/fisher/issues/594
This should fix: #556

fisher self-update deprecated -> use fisher update

---

src/steps/upgrade.vim

The project https://github.com/wsdjeg/dein-ui.vim provides a userfriendly alternative to the `call dein#upgrade` call of the dein plugin manager. If this command is available, we should run it

Vim update: call DeinUpdate if available

---

src/config.rs
src/main.rs
src/steps/generic.rs

gcloud is the command line tool for interacting with Google Cloud Platform. It's the CLI you can use to do typical tasks like creating new virtual servers. But you can also use it to install "components", like installing the `kubectl` command to interact with a Google Kubernetes Engine instance, or a local emulator for some of their closed-source products. So `gcloud components update` will check for updates on gcloud itself and any components you have installed. The `--quiet` flag skips confirmation, but it still outputs a changelog for the things that were updated.
I have tested that this runs the command like I expect and outputs properly, and that Topgrade understands that it was successful. Also, I've verified that if there are no updates available, it can determine that quickly and …

Add support for upgrading gcloud

---

src/executor.rs
src/steps/zsh.rs
src/utils.rs

* Fixes #569
* Mostly made this for fun. Not sure if this is the best way to handle the situation, I don't have too much experience with OSS. 
* Adds a new that allows you to specify output codes that are valid for a given script.
* Also fixes issue with oh-my-zsh spitting out an 80 output if no changes were made

Fixes issue with ohmyzsh returning 80 on a successful run

---

src/executor.rs
src/utils.rs

This one isn't entirely necessary, but it eliminates some of the duplication created by my previous PR.

Removes unnecessary duplication with a blanket implementation

---

src/steps/powershell.rs

Run Powershell with -NoProfile (Fix #582)

---

config.example.toml
src/config.rs
src/steps/os/linux.rs

Enable distro-sync in Fedora (fix #587)

---

src/steps/os/unix.rs

Noticed new Brew Cask step failing after upgrading topgrade.
Fix was to switch args from `brew --cask upgrade` to `brew upgrade --cask`

Fix Brew Cask step argument order

---

src/steps/generic.rs

Skip dotnet when no SDK is installed (fix #592)

---

src/steps/os/linux.rs

This is just a small change which supresses the fetching of arch news when paru is used, since it is done automatically when  `paru` is executed. I am not that well versed in rust, hope it is still an okayish way to do this.

Surpress explicit news printing when paru is used

---

src/steps/vim.rs

This PR adds support for the Neovim step for users which use `init.lua` in lieu of `init.vim` for configuration. It only adds a fallback check for the appropriate path; nothing else in the Neovim step has been changed.

Fix: Neovim may use init.vim or init.lua

---

Cargo.lock
src/main.rs
src/terminal.rs

Use console's read_key instead of read_char

---

src/config.rs
src/main.rs
src/steps/generic.rs

- [*] I also tested that Topgrade skips the step where needed: *kind of, by giving `utils::require` a wrong binary name*
---
This PR adds support for plugins for [micro](https://micro-editor.github.io/) via its built-in `-plugin update` command.
Unfortunately I have to check micro's stdout, because even if it fails, micro returns exit code 0. See https://github.com/zyedidia/micro/issues/1647
**Excerpts:**
Normal run:
```
❯ cargo run -- --only micro             
Finished dev [unoptimized + debuginfo] target(s) in 0.06s
Running `target/debug/topgrade --only micro`
―― 14:48:36 - micro ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Checking for plugin updates
Nothing to install / update
―― 14:48:36 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
micro: OK …
```

Add plugin support for the micro text editor

---

src/steps/generic.rs

closes #647
Example output with `-v`
```
―― 09:32:34 - Visual Studio Code ―――――――――――――――――――――――――――――――――――――――――――――――
2021-02-22T08:32:34.882Z DEBUG topgrade::executor   > Running "/usr/bin/code" "--force" "--install-extension" "alphabotsec.vscode-eclipse-keybindings" "--install-extension" "eamodio.gitlens" "--install-extension" "formulahendry.code-runner" "--install-extension" "ms-azuretools.vscode-docker" "--install-extension" "ms-python.python" "--install-extension" "muhammad-sammy.csharp" "--install-extension" "redhat.vscode-xml" "--install-extension" "redhat.vscode-yaml" "--install-extension" "rogalmic.bash-debug" "--install-extension" "rust-lang.rust" "--install-extension" "serayuzgur.crates" "--install-extension" "webfreak.debug" "--install-extension" …
```

Install VSCode extensions with a single command

---

src/steps/upgrade.vim

this PR adds support for the neovim plugin manager [paq-nvim](https://github.com/savq/paq-nvim)

add support for paq-nvim

---

src/main.rs
src/steps/generic.rs

The GOPATH env variable usually is not set on any system because Go
uses its own env management via `go env` command.
Also `go env GOPATH` is not on all systems the same as `$HOME/go`.
On such systems topgrade would use the wrong GOPATH.
If the `go` command is installed then `go env GOPATH` will always print
something.
If GOPATH is set then `go env GOPATH` will print the value of GOPATH,
otherwise `go env GOPATH` will print the GOPATH value of the Go env
config.

Use go env GOPATH to determine the GOPATH

---

src/config.rs
src/executor.rs
src/main.rs
src/steps/generic.rs

With the release of Go 1.16 the behavior of `go get` has been changed.
In previous Go versions `go get` was used not only to add module
dependencies but also to install Go tools.
As of Go 1.16 `go get` can only add and upgrade module dependencies.
To install Go tools now the `go install` command has to be used.
Further on Go 1.16 enabled the GOMODULE mode by default and will drop
the GOPATH mode completly in Go 1.17.
So the package definition `all` like in `go get -u all` does not work
anymore if the PWD is outside of a Go module project.
Because of this `go list all` also does not work for the same reason.
That being said it seems that currently there is no way to get a list of
all installed Go tools or packages at the GOPATH level.
So the only possible solution to determine the …

Drop the Go step

---

src/steps/remote/ssh.rs

Execute the user default shell when using remotes (fix #670)

---

config.example.toml
src/config.rs
src/steps/os/linux.rs

This commit makes it possible to *not* to use `rpm-ostree` even on
systems where it is detected.
This commit is fully backwards compatible with previous releases, and
without changing the config file all previous behaviors are the exact
same.
This commit adds the `rpm_ostree` field in the `[linux]` table of the
configuration, and defaults to `true`. This means Topgrade will first
check if `/usr/bin/rpm-ostree` exists, and only if so then check if the
user does not want to use `rpm-ostree` via the configuration. If the
user *does not* want to use `rpm-ostree`, then normal operation
continues checking for DNF or YUM.
This makes it possible for people where `rpm-ostree` is installed, but
where the system is not an `ostree` based distribtuion. This happens
when people are using things like …

makes rpm-ostree configurable

---

src/config.rs
src/main.rs
src/steps/generic.rs

This PR adds support to manage [bin](https://github.com/marcosnils/bin) updates

Add bin support

---

src/main.rs

Fixes a typo by changing "sucessfully" to "successfully".

Fix Sucessfully Typo

---

src/steps/generic.rs

Under certain circumstances, e.g. on macOS 12, invoking `pip3` produces the following warning: `WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip. Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue. To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.`

PIP: avoid the warning 'pip is being invoked by an old script wrapper'

---

src/main.rs
src/steps/node.rs

Adds support for [pnpm](https://github.com/pnpm/pnpm) global update.
2 questions:
- Should I check like for `npm` if `pnpm root -g` inside the user's home directory ? Like `yarn`, the default global directory is located at `~/pnpm-global`, so I don't think this shoud be necessary.
- Should I add the `--silent` flag ? I prefer without it to see what's going on, but maybe it's better if silent.
Thanks for this super useful program!

Adding pnpm support

---

config.example.toml
src/config.rs
src/steps/os/linux.rs

This change adds an option, `firmware.upgrade`, that if set to `false` only checks for and displays available firmware updates. If set to `true` (default) the user is offered to run the firmware upgrade.

Make firmware upgrade configurable

---

config.example.toml
src/config.rs
src/main.rs
src/steps/os/linux.rs

This change adds the option `flatpak.use_sudo` that allows to update the system-wide installation with sudo. When set to `true` the system-wide installation will be updated with sudo. If set to `false` (default) the update will be run as regular user.
This solves the problem where running `flatpak update` on a remote system fails if run as regular user.
Fixes #737.

Allow to run `flatpak update` with sudo

---

src/config.rs
src/main.rs
src/steps/generic.rs

This adds support for a new step of [chezmoi](https://github.com/twpayne/chezmoi), a dotfile manager for managing all of your precious dotfiles

Adds support for chezmoi

---

src/main.rs
src/steps/node.rs

Deno can be installed from cargo or arch linux's repositories, so upgrade should only be called for user-wide shell-script installations.

Skip deno upgrade unless installed under .deno

---

src/main.rs
src/steps/os/android.rs
src/steps/os/mod.rs

This PR adds support for Android, more specifically [Termux](https://termux.com/), a very popular terminal emulator and Linux environment. It updates Termux packages (using `pkg` and `apt`) and other already supported UNIX tools (on my device, that meant `cargo`, `npm`, `nvim`, `yadm`, `git repositories`, `tmux` (`TPM`) and `pip3`). It also correctly started in a new `tmux` session, if that config is enabled.
Building is done with `cargo build --target aarch64-linux-android`.
I have one question: rebooting is not useful in this case and only works on rooted devices anyway, should the code be modified to remove this option on Android?
Let me know if there is anything that can or should be improved.

Add Android/Termux support

---

src/config.rs
src/main.rs
src/report.rs
src/steps/emacs.rs
src/steps/generic.rs
src/steps/git.rs
src/steps/node.rs
src/steps/os/dragonfly.rs
src/steps/os/freebsd.rs
src/steps/os/linux.rs
src/steps/os/macos.rs
src/steps/os/unix.rs
src/steps/os/windows.rs
src/steps/powershell.rs
src/steps/remote/ssh.rs
src/steps/remote/vagrant.rs
src/steps/tmux.rs
src/steps/vim.rs
src/steps/zsh.rs
src/terminal.rs
src/utils.rs

Highlights:
- Use `impl IntoIterator` for arrays to remove some ampersands
- Use nested or patterns where applicable

Add minor refactorings

---

topgrade.8

It was confusing since it was outdated

Remove date and version information from man page

---

src/config.rs
src/main.rs
src/steps/os/linux.rs

This PR adds a step to execute [`pacdiff`](https://man.archlinux.org/man/pacdiff.8.en). It is run with `sudo` since it needs to edit files in `/etc` and it can be disabled.
Checks:
This PR closes #794

Add new step pacdiff

---

src/config.rs
src/main.rs
src/steps/generic.rs

Runs `spicetify upgrade` whenever `spicetify` is found in PATH, errors based on the command's status code. Closes #797
Just to be sure, can you test this? @CryoRenegade

Add Support for Spicetify

---

topgrade.8

Wordings & argument format
How step lists should be provided was not documented at all and not intuitive either
- [-] The code compiles (`cargo build`)
- [-] The code passes rustfmt (`cargo fmt`)
- [-] The code passes clippy (`cargo clippy`)
- [-] The code passes tests (`cargo test`)
- [-] I also tested that Topgrade skips the step where needed

Improve man page

---

src/steps/os/android.rs

Fix Android code following the addition of "Selective yes" (#802 #808).

Fix code for Android and selective yes

---

src/steps/os/linux.rs

On a rpm-ostree based system, topgrade would previously fail to detect
the rpm-ostree executable and fall back to yum instead, which isn't
available. This was caused by constructing a Path instance with
`Path::new`, rather than querying the underlying OS for a path to the
rpm-ostree executable.
Make the `system` update step use `which` to determine if an executable
called "rpm-ostree" is available on the system and get the correct path
to the executable.
I developed this code myself.

Linux: System: Fix rpm-ostree detection

---

src/steps/os/linux.rs

fix: pacstall should run without yay arguments

---

src/config.rs
src/main.rs
src/steps/generic.rs

go-global-update (https://github.com/Gelio/go-global-update) is a small
tool to update all executables installed in a user's GOBIN, effectively
providing a `go get -u all` replacement for Go 1.16+.
Since it appears that Go will not be receiving a built-in way to do this
in the near future, this could be a good option in the meantime.

Re-add the Go step via go-global-update

---

src/config.rs
src/main.rs
src/steps/mod.rs
src/steps/toolbx.rs

This adds a module to upgrade all toolboxes found on a host system.
[Toolbox][1] (More recently: `toolbx`) is a tool that easily provides
mutable, containerized command line environments. It is a means to work
and develop in a mutable environment on immutable operating systems such
as Fedora Silverblue, CoreOS, Kinoite and much more. However, it is not
limited to these use cases.
The integration into topgrade works as follows: Toolbx makes many of the
hosts folders available form inside the toolbx container by default. In
particular, all of the hosts filesystem is mapped under `/run/host`. This
module exploits this fact by:
- Gathering a list of toolboxes …

Enable updating Toolbx through topgrade

---

src/steps/os/archlinux.rs

Just a small typo I noticed while checking the code flow.

Fix typo in `box_pacakge_manager`

---

src/steps/os/linux.rs

Previously when performing the "system" upgrade step, rpm-ostree would
be passed a "--yes" argument when it was configured in topgrade.
However, this is not an option available for rpm-ostree, so it would
cause an error and abort execution of the updates.
*Note Clippy doesn't pass, but that's due to an unused import unrelated to this PR*

linux: Ignore "--yes" for rpm-ostree upgrade

---

src/config.rs
src/main.rs
src/steps/kakoune.rs
src/steps/mod.rs
src/steps/upgrade.kak

I based this off of the vim plugin updater. unfortunately kak-plug does not seem to have a easy way of outputting it's progress and result. I do believe it's possible, but am unsure if such hacks would be welcome.

Support for updating kakoune plugins with kak-plug

---

src/steps/upgrade.vim

`dein` is a plugin manager for vim, which was supported for a while in
an earlier version of topgrade. This patch reintroduces support for
upgrading "plain" `dein`, rather that the `dein` UI which is invoked by
`DeinUpdate` in vim.
The commit that initially introduced `dein` support as implemented here was 57d3893a2b960e6c4fc8460f6bf4c3f30f546e20, but it got removed from topgrade in 5fb9b4177110d9e4890ab5eeca3f335d311b1b29. I didn't find any reason for that, did it happend on purpose?

vim: Support updating dein

---

src/config.rs
src/main.rs
src/steps/containers.rs
src/steps/mod.rs

This PR implements automatic updates for all available ~~podman~~podman/docker containers in the user installation (not roots containers). 
I'm aware of the discussion in #214, so I made the code respect the tags that the containers were initially pulled with to ensure that no semver-breaking changes are performed when a specific tag was checked out initially (Like rust does with Cargo.toml).
The code is still very rough in a lot of places, but I wanted to put it up for discussion before finishing it entirely. If your opinion from #214 still holds, feel free to close the issue immediately.

Upgrade podman/docker containers

---

src/config.rs
src/main.rs
src/steps/generic.rs

Hi there!
This PR adds support for upgrading GitHub CLI extensions, which are custom commands for the [GitHub CLI](https://cli.github.com/) that anyone can create and use. Once installed locally, they can be upgraded from their respective upstream repos.
See https://docs.github.com/en/github-cli/github-cli/using-github-cli-extensions
This fixes #868 
Since this is my very first PR to this repo, please do let me know if things should be done differently.
Thanks.

Add support for upgrading GitHub CLI Extensions

---

src/steps/containers.rs

Use the same format for all `docker image` commands

Use `docker image ls` instead of `docker images` to list images

---

src/main.rs

Fix capitalization of GitHub

---

src/terminal.rs

you can always press q to quit so it should also always be displayed

Always display quit

---

src/main.rs
src/steps/generic.rs
src/steps/os/unix.rs

- fix(os/unix): cannot find `SkipStep` while building for android
- feat: enable `tlmgr` updates for android
Closes #895

Fix building for Android, enable `tlmgr` updates

---

config.example.toml

The option name is now `pull_predefined`. This commit fixed the template config with the new option name

Fix: correct option name

---

.github/workflows/main.yml
.github/workflows/release-cross.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
src/config.rs
src/main.rs

Upgrade arg parsing to clap v3, take two

---

src/config.rs

Fix docs of arch_package_manager fn

---

.vscode/launch.json
src/steps/generic.rs

pip should be executed via the regular python executable

---

src/steps/os/unix.rs

Don't try to upgrade nix if it's not a part of a profile

---

.vscode/tasks.json
src/config.rs
src/main.rs
src/steps/os/linux.rs

Support deb-get

---

src/config.rs

Restore old argument behavior

---

Cargo.lock
Cargo.toml
src/steps/node.rs

As of https://github.com/npm/cli/releases/tag/v8.11.0 npm deprecated `-g` syntax replaced with `--location=global`
```
―― 16:27:28 - Node Package Manager ―――――――――――――――――――――――――――――――――――――――――――――
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
```

npm/cli 8.11.0 deprecated -g flags

---

.vscode/topgrade.code-snippets
src/config.rs
src/main.rs
src/steps/os/macos.rs

Sparkle for updates

---

config.example.toml
src/config.rs
src/steps/os/archlinux.rs

I have not tested the patch yet but I will at first opportunity.
Additionally, I have no implemented cleanup yet. I am still researching how Pamac does this through the CLI.

Add Pamac support

---

Cargo.toml
src/steps/os/unix.rs

This subcommand is unavailable when the `sdkman_selfupdate_feature`
option is disabled, as is the case when SDKMAN! is installed via
Homebrew.
https://github.com/sdkman/sdkman-cli/pull/1042

Ensure `selfupdate` is enabled for SDKMAN!
